### PR TITLE
Adding Exomiser to pipeline

### PR DESCRIPTION
**Pull request by SophieS9**
- Changes to add exomiser functionality to pipeline - added processes to nf script, relevant config and accessory scripts in bin. Based entirely on current process within dragenwgs_post_processing, no modifications made. 
- Exomiser itself needs it's own environment due to a java version conflict with gatk3.8. Therefore environment yaml made and environment created on transfer account. 
- Updated make_database_config.py to now add referral and hpoIDs. 
- Bumped version

Tested on /data/output/results/211215_NB551415_0311_AHC3C3BGXK/NonocusWES38/ 
post processing run 5 (no hpo terms in variables files)
post processing run 6 (hpo terms in variables files)

Data uploaded to VariantBank and variants now include Exomiser score when provided.

### CODE REVIEW

**Review by josephhalstead — COMMENTED** [review]
- can we update clinvar VCF to same as dragenwgs?

- Can we clean up the exomier env - only needs the java and python dependencies

**Comment by SophieS9** [comment]
Environment cleaned up for exomiser and clinvar updated to match dragenwgs_post_processing development. Tested in /data/output/results/211215_NB551415_0311_AHC3C3BGXK/NonocusWES38/ 
post processing run 7.

Output uploaded to VariantBank and still working

**Comment by josephhalstead** [comment]
testing on 220819_A00748_0298_BH52TFDRX2

**Comment by josephhalstead** [comment]
merging into dev for final test

**Pull request merged**
