### PR TITLE
Whole Exome Sequencing

### PR DESCRIPTION
**Pull request by SophieS9**
Adding in all changes needed for the whole exome sequencing additions to the pipeline.

See CC-21-005-GEN for full details on the validation.

Also tested TSO pipeline to ensure this still functioned correctly using run 210309_NB551319_0184_AHGKGNBGXH.

Linked to update to DragenGE pipeline - https://github.com/AWGL/DragenGE/pull/7

### CODE REVIEW

**Review by josephhalstead — COMMENTED** [review]
same as DragenGE just change name of IlluminaTruSightOne38 files

**Review by josephhalstead — CHANGES_REQUESTED** [review]
See DragenGE

**Comment by SophieS9** [comment]
Renamed IlluminaTruSightOne38 config files.

**Review by josephhalstead — APPROVED** [review]
all good now

**Pull request merged**
